flat_pmbb_phewas.Rmd:
  path: dev/flat_pmbb_phewas.Rmd
  state: active
  R: R/awk_str_filter.R
  tests: tests/testthat/test-awk_str_filter.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_pmbb_phewas.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask
