flat_pmbb_phewas.Rmd:
  path: dev/flat_pmbb_phewas.Rmd
  state: active
  R:
  - R/apply_variant_masks.R
  - R/awk_str_filter.R
  - R/pmbb_extract_genotype_masks.R
  - R/pmbb_extract_genotypes.R
  - R/pmbb_format_phecodes.R
  - R/render_pmbb_phewas_report.R
  - R/run_pmbb_phewas.R
  - R/run_pmbb_phewas_report.R
  tests:
  - tests/testthat/test-awk_str_filter.R
  - tests/testthat/test-apply_variant_masks.R
  - tests/testthat/test-pmbb_extract_genotypes.R
  - tests/testthat/test-pmbb_extract_genotype_masks.R
  - tests/testthat/test-pmbb_format_phecodes.R
  - tests/testthat/test-run_pmbb_phewas.R
  - tests/testthat/test-run_pmbb_phewas_report.R
  - tests/testthat/test-render_pmbb_phewas_report.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_pmbb_phewas.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask
