# WARNING - Generated by {fusen} from dev/flat_pmbb_phewas.Rmd: do not edit by hand

test_that("render_pmbb_phewas_report works", {
  expect_true(inherits(render_pmbb_phewas_report, "function"))

  skip()
  render_pmbb_phewas_report(
    phewas_output = "/project/damrauer_shared/Users/mglevin/pmbbPheWASr/tests/testthat/cftr_phewas_results.rds",
    mask_output = "/project/damrauer_shared/Users/mglevin/pmbbPheWASr/tests/testthat/cftr_mask_results.rds",
    output_file = "cftr_report.html"
  )
})
