# WARNING - Generated by {fusen} from dev/flat_pmbb_phewas.Rmd: do not edit by hand

test_that("pmbb_filter_exome_annotations works", {
  
  res <- pmbb_filter_exome_annotations_gene(annotations_filename = "/project/PMBB/PMBB-Release-2020-2.0/Exome/Variant_annotations/PMBB-Release-2020-2.0_genetic_exome_variant-annotation-counts.txt",
                              gene_names = c("LDLR"))
  
  expect_true(inherits(pmbb_filter_exome_annotations_gene, "function"))
  expect_true(tibble::is_tibble(res))
})
