# WARNING - Generated by {fusen} from dev/flat_pmbb_phewas.Rmd: do not edit by hand

test_that("pmbb_format_phecodes works", {
  expect_true(inherits(pmbb_format_phecodes, "function"))
  phecode_file <- "phecodes.tsv"
  if (!file.exists(phecode_file)) {
    # The path to use during dev in the flat file
    phecode_file <- file.path("tests", "testthat", phecode_file)
    if (!file.exists(phecode_file)) {
      stop(phecode_file, " does not exist")
    }
  }

  res <- pmbb_format_phecodes(phecode_file)
  expect_true(tibble::is_tibble(res))
})

test_that("pmbb_format_covariates works", {
  expect_true(inherits(pmbb_format_covariates, "function")) 
  
  testthat::skip_if(testthat:::on_ci() | testthat:::on_cran())
  
  pmbb_covariates_res <- pmbb_format_covariates(
  covariate_files = c("/project/PMBB/PMBB-Release-2020-2.0/Phenotype/2.3/PMBB-Release-2020-2.3_covariates.txt", "/project/PMBB/PMBB-Release-2020-2.0/Phenotype/2.1/PMBB-Release-2020-2.1_phenotype_covariates.txt"),
  populations = c("ALL", "EUR"),
  covariate_population_col = Class,
  covariate_cols = c(Age = Age_at_Enrollment, Sex = Gen_Sex, dplyr::starts_with("Genotype_PC"))
)
  
  expect_true(inherits(pmbb_covariates_res, "data.frame"))
  
})
