# WARNING - Generated by {fusen} from dev/flat_pmbb_phewas.Rmd: do not edit by hand

test_that("apply_variant_masks works", {
  expect_true(inherits(apply_variant_masks, "function")) 
})

test_that("filter_dataframe works", {
  res <- filter_dataframe(dplyr::starwars, list(height = " > 100", eye_color = " == 'blue'"))
  expect_true(inherits(filter_dataframe, "function")) 
  expect_true(tibble::is_tibble(res))
  expect_true(nrow(res) > 0)
})

test_that("filter_dataframe errors on missing columns", {
  expect_error(filter_dataframe(dplyr::starwars, list(missing_column_name = " > 100", eye_color = " == 'blue'")))
})
