# WARNING - Generated by {fusen} from dev/flat_pmbb_phewas.Rmd: do not edit by hand

test_that("awk_str_filter works", {
  res <- awk_str_filter(filename = "/project/PMBB/PMBB-Release-2020-2.0/Exome/Variant_annotations/PMBB-Release-2020-2.0_genetic_exome_variant-annotation-counts.txt",
               filter_col = "Gene.refGene",
               filter_str = c("LDLR"))
  expect_true(inherits(awk_str_filter, "function")) 
  expect_true(tibble::is_tibble(res))
})
