# WARNING - Generated by {fusen} from dev/flat_pmbb_phewas.Rmd: do not edit by hand

test_that("pmbb_extract_genotypes works", {
  expect_true(inherits(pmbb_extract_genotypes, "function"))

  testthat::skip_if(testthat:::on_ci() | testthat:::on_cran())

  ldlr_file <- "ldlr_df.tsv"
  if (!file.exists(ldlr_file)) {
    # The path to use during dev in the flat file
    ldlr_file <- file.path("tests", "testthat", ldlr_file)
    if (!file.exists(ldlr_file)) {
      stop(ldlr_file, " does not exist")
    }
  }

  ldlr_variants <- data.table::fread(ldlr_file)

  ldlr_genotype_res <- pmbb_extract_genotypes(
    variant_df = ldlr_variants,
    variant_id_col = ID,
    effect_allele_col = Alt,
    plink_bin = "/project/voltron/Applications/PLINK/plink2_linux_avx2_20230607/plink2",
    bfile = "/project/PMBB/PMBB-Release-2020-2.0/Exome/pVCF/all_variants/PMBB-Release-2020-2.0_genetic_exome_GL"
  )
  expect_true(tibble::is_tibble(ldlr_genotype_res))
})
