# WARNING - Generated by {fusen} from dev/flat_pmbb_phewas.Rmd: do not edit by hand

#' Apply variant masks to annotation file
#' 
#' This function applies variant mask criteria to a data frame containing variant annotations. The function can accept multiple sets of filter criteria, each defined as a list of column names and filter conditions. The resulting filtered data frames are returned as a named list.
#' 
#' @param annotation_df A data frame to be filtered.
#' @param masks A named list of lists containing filter criteria.
#'   Each element of the outer list should be named after the desired output name for the filtered data frame (eg. name of the variant mask).
#'   Each inner list should contain the filter criteria for a specific set of columns.
#'   For example: list(plof_0.001 = list(ExonicFunc.ensGene = "= stopgain", gnomAD_exome_ALL = "< 0.001"), common_0.01 = list(gnomAD_exome_ALL = "> 0.01"))
#'   
#' @return A named list of filtered [tibble::tibble()]s based on the provided filter criteria.
#' 
#' @export
#' @examples
#' \dontrun{ 
#' apply_variant_masks(ldlr_variants, masks = list(plof_0.001 = list(ExonicFunc.ensGene = "== 'stopgain'", gnomAD_exome_ALL = "< 0.001"), 
#'                                                 common_0.01 = list(gnomAD_exome_ALL = "> 0.01"), 
#'                                                 exonic_0.001 = list(Func.refGene = "== 'exonic'", gnomAD_exome_ALL = "< 0.001")))
#' }

apply_variant_masks <- function(annotation_df, masks) {
  # Check if the input is a data frame
  if (!is.data.frame(annotation_df)) {
    rlang::abort("Input must be a data frame.")
  }
  
  # Check if the masks is a list
  if (!is.list(masks)) {
    rlang::abort("Masks must be provided as a list.")
  }
  
  # Apply the filter criteria to the data frame for each mask
  filtered_dfs <- purrr::map(masks, function(mask) {
    filter_dataframe(annotation_df, mask)
  })
  
  # Set the names of the filtered data frames based on the names of the masks
  names(filtered_dfs) <- names(masks)
  
  return(filtered_dfs)
}
