# WARNING - Generated by {fusen} from dev/flat_pmbb_phewas.Rmd: do not edit by hand

#' Filter arbitrary rows from a tab-delimited text file using awk
#'
#' This function wraps the system command `awk` to efficiently filter rows from a tab-delimited text file. The function accepts the path to a tab-delimited text file, name of a column to filter, and the string to filter for. The function returns a tibble containing the filtered rows.
#'
#' @param filename The path to the tab-delimited text file.
#' @param filter_col The name of the column to filter.
#' @param filter_str A character vector of strings to filter for in the specified column.
#'
#' @return
#'
#' A [tibble::tibble()] containing the filtered rows from the input file
#'
#' @export
#'
#' @examples
#' \dontrun{
#' ldlr_variants <- awk_str_filter(
#'   filename = "/project/PMBB/PMBB-Release-2020-2.0/Exome/Variant_annotations/PMBB-Release-2020-2.0_genetic_exome_variant-annotation-counts.txt",
#'   filter_col = "Gene.refGene",
#'   filter_str = c("LDLR"))
#' }
awk_str_filter <- function(filename, filter_col, filter_str) {
    # Check if the file exists
    if (!file.exists(filename)) {
        cli::cli_abort("File does not exist: {filename}")
    }
    
    cli::cli_progress_step("Extracting '{filter_str}' from column '{filter_col}' in {.file {filename}}")
  
    # Determine the column index based on the filter_col
    header <- readLines(filename, n = 1)
    col_names <- strsplit(header, "\t")[[1]]
    col_index <- which(col_names == filter_col)

    if (length(col_index) == 0) {
        cli::cli_abort("Column not found: {filter_col}")
    }

    # Construct the awk command
    # awk_cmd <- paste0("awk -F'\t' '", paste0("$", col_index, " ~ /", paste(filter_str, collapse = "|"), "/"), "' ", shQuote(filename))
    
    awk_cmd <- c(paste0("NR == 1 || ", paste0("($", col_index, " == \"", filter_str, "\")", collapse = " || ")), filename)
    
    # Execute the awk command using processx
    result <- processx::run(
        command = "awk",
        args = awk_cmd,
        error_on_status = TRUE
    )

    # Check if the command executed successfully
    if (result$status != 0) {
        cli::cli_abort("Error executing awk command: {result$stderr}")
    }

    # Format the filtered output using data.table::fread()
    filtered_dt <- data.table::fread(
        text = result$stdout,
        sep = "\t",
        header = TRUE,
        stringsAsFactors = FALSE,
        quote = "", 
        na.strings = "."
    )

    # Convert the data.table to a tibble
    filtered_tibble <- tibble::as_tibble(filtered_dt)

    return(filtered_tibble)
}

