# WARNING - Generated by {fusen} from dev/flat_pmbb_phewas.Rmd: do not edit by hand

#' Filter the PMBB whole exome sequence annotations file
#' 
#' This function filters the variant annotations file to only include variants within the specified gene. Because the variant annotation file is extremely large, this function wraps the `awk` shell command
#' 
#' @param annotations_filename Path to the PMBB whole-exome sequencing variant annotations file
#' @param gene_names A character vector of gene names used to filter the variant annotations file 
#'
#' @return
#' A [tibble::tibble()] containing the filtered variant annotations 
#' 
#' 
#' @export
#' @examples
#' pmbb_filter_exome_annotations_gene(annotations_filename = "/project/PMBB/PMBB-Release-2020-2.0/Exome/Variant_annotations/PMBB-Release-2020-2.0_genetic_exome_variant-annotation-counts.txt",
#'                               gene_names = c("LDLR"))

pmbb_filter_exome_annotations_gene <- function(annotations_filename, gene_names) {
  
  cli::cli_progress_step("Extracting {gene_names} from {.file {annotations_filename}}")
  
  exome_gene_annotations_filtered <- processx::run("awk",
    args = c(paste0("NR == 1 || ", paste0("($8 == \"", gene_names, "\")", collapse = " || ")), annotations_filename),
    echo = FALSE,
    echo_cmd = FALSE
  )
  
  exome_gene_annotations_df <- data.table::fread(text = exome_gene_annotations_filtered$stdout) %>%
    tibble::as_tibble()
  
  return(exome_gene_annotations_df)
}
