# WARNING - Generated by {fusen} from dev/flat_pmbb_phewas.Rmd: do not edit by hand

#' Render PheWAS Report
#' 
#' This function renders an HTML report from pre-saved genotype mask and PheWAS output files.
#' 
#' @param mask_output_path Path to the saved genotype output for each mask
#' @param phewas_output_path Path to the saved PheWAS output dataframe
#' @param output_file Full path to save the HTML report
# @param gene Character vector of gene name(s) analyzed in the PheWAS
#' 
#' @return Path to the HTML report
#' 
#' @export
#' @examples
#' \dontrun{
#' render_pmbb_phewas_report()
#' }
render_pmbb_phewas_report <- function(mask_output_path, phewas_output_path, output_file) {
  
  # Get the function call as a string
  # function_call <- deparse(sys.call(-1))
  
  # # Collapse the gene names into a single string
  # gene_names_collapsed <- glue::glue_collapse(gene, sep = "-")
  
  # Render the Quarto document using the saved files, function call, and gene names as execute_params
  
  if(!file.exists(".phecode_phewas_templated.qmd")) {
   usethis::use_template(".phecode_phewas_template.qmd", package = "pmbbPheWASr")
  }
  
  quarto::quarto_render(
    input = ".phecode_phewas_template.qmd",
    output_format = "html",
    execute_params = list(
      mask_results = fs::path_abs(mask_output_path),
      phewas_results = fs::path_abs(phewas_output_path)
    ),
    output_file = output_file
  )
  
  # fs::file_delete(".phecode_phewas_template.qmd")
  
  # Return the path to the generated report file
  return(output_file)
}
