# WARNING - Generated by {fusen} from dev/flat_pmbb_phewas.Rmd: do not edit by hand

#' Run a PheWAS and generate a report
#' 
#' This function is a wrapper around the `run_pmbb_phewas` function that additionally generates an HTML report of the results.
#' 
#' 
#' @inheritParams run_pmbb_phewas
#' @inheritParams pmbb_extract_genotype_masks
#' @inheritParams render_pmbb_phewas_report
#' 
#' @return A named list containing the paths to the output files
#' 
#' @export
#' @examples
#' \dontrun{
#' run_pmbb_phewas_report(
#'   gene = c("LDLR"),
#'   annotation_file = "/project/PMBB/PMBB-Release-2020-2.0/Exome/Variant_annotations/PMBB-Release-2020-2.0_genetic_exome_variant-annotation-counts.txt",
#'   gene_col = "Gene.refGene",
#'   masks = list(
#'     plof_0.01 = list(ExonicFunc.ensGene = "%in% c('stopgain', 'stoploss', 'frameshift substitution')", gnomAD_exome_ALL = "< 0.01"),
#'     missense_0.01 = list(ExonicFunc.ensGene = "%in% c('nonsynonymous SNV')", gnomAD_exome_ALL = "< 0.01")
#'   ),
#'   mask_operator = list(
#'     plof_0.01 = "burden",
#'     missense_0.01 = "burden"
#'   ),
#'   variant_id_col = ID,
#'   effect_allele_col = Alt,
#'   populations = c("ALL"),
#'   covariate_population_col = "Class",
#'   covariate_cols = c(Age = Age_at_Enrollment, Sex = Gen_Sex, dplyr::starts_with("Genotype_PC")),
#'   mask_output_path = "LDLR_mask_results.rds",  # Optional: Specify the output path for the mask results file
#'   phewas_output_path = "LDLR_phewas_results.rds",  # Optional: Specify the output path for the PheWAS results file,
#'   phecode_file = "/project/PMBB/PMBB-Release-2020-2.0/Phenotype/2.3/PMBB-Release-2020-2.3_phenotype_PheCode-matrix.txt",
#'   covariate_files = c("/project/PMBB/PMBB-Release-2020-2.0/Phenotype/2.3/PMBB-Release-2020-2.3_covariates.txt", "/project/PMBB/PMBB-Release-2020-2.0/Phenotype/2.1/PMBB-Release-2020-2.1_phenotype_covariates.txt"),
#'   bfile = "/project/PMBB/PMBB-Release-2020-2.0/Exome/pVCF/all_variants/PMBB-Release-2020-2.0_genetic_exome_GL",
#'   plink_bin = "/project/voltron/Applications/PLINK/plink2_linux_avx2_20230607/plink2",
#'   cores = 16
#' )
#' }
run_pmbb_phewas_report <- function(gene, annotation_file, gene_col, masks, mask_operator, variant_id_col, effect_allele_col, plink_bin, bfile, phecode_file, covariate_files, populations, covariate_population_col, covariate_cols, mask_output_path = NULL, phewas_output_path = NULL, report_output_path = NULL, ...) {
  
  # Extract genotypes for a series of masks
  mask_res <- pmbb_extract_genotype_masks(
    gene = gene,
    annotation_file = annotation_file,
    gene_col = gene_col,
    masks = masks,
    mask_operator = mask_operator,
    variant_id_col = {{ variant_id_col }},
    effect_allele_col = {{ effect_allele_col }},
    plink_bin = plink_bin,
    bfile = bfile
  )
  
  # Save the mask results to a file
  if (is.null(mask_output_path)) {
    # Use a temporary file if mask_output_path is not provided
    mask_output_path <- tempfile(fileext = ".rds")
  }
  saveRDS(mask_res, file = mask_output_path)
  
  # Run a PheWAS
  phewas_res <- run_pmbb_phewas(
    mask_genotypes_list = mask_res,
    phecode_file = phecode_file,
    covariate_files = covariate_files,
    populations = populations,
    covariate_population_col = {{ covariate_population_col }},
    covariate_cols = {{ covariate_cols }},
    ...
  )
  
  # Save the PheWAS results to a file
  if (is.null(phewas_output_path)) {
    # Use a temporary file if phewas_output_path is not provided
    phewas_output_path <- tempfile(fileext = ".rds")
  }
  saveRDS(phewas_res, file = phewas_output_path)
  
  # Collapse the gene names into a single string
  gene_names_collapsed <- glue::glue_collapse(gene, sep = "-")
  
  # Generate a timestamp for the output file name
  timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
  
  # Generate the output file name with the timestamp and collapsed gene names
  output_file <- paste0(gene_names_collapsed, "_", "phewas_report_", timestamp,".html")
  
  # Set the full output file path
  if (!is.null(report_output_path)) {
    output_file <- fs::path(report_output_path, output_file)
  }
  
  # Render the PheWAS report
  render_pmbb_phewas_report(
    mask_output_path = mask_output_path,
    phewas_output_path = phewas_output_path,
    output_file = output_file
  )
  
  # Return the paths to the saved mask, PheWAS results, and report files
  return(list(
    report_output_path = output_file,
    mask_output_path = mask_output_path,
    phewas_output_path = phewas_output_path
  ))
}
